apiVersion: v1
kind: ConfigMap
metadata:
  name: order-html
  namespace: apps
data:
  index.html: |
    <html>
      <body style="font-family:Arial; font-size:40px;">
        <h1>This is ORDER Page</h1>
      </body>
    </html>